# Uses the official Python 3.9.18 Alpine Linux image as the base
FROM python:3.9.18-alpine3.18
# Installs essential build tools for compiling dependencies.
RUN apk add build-base
# Installs PostgreSQL development libraries and necessary compilers
RUN apk add postgresql-dev gcc python3-dev musl-dev

ARG FLASK_APP
ARG FLASK_ENV
ARG DATABASE_URL
ARG SCHEMA
ARG SECRET_KEY
# Sets the working directory inside the container.
WORKDIR /var/www

COPY requirements.txt .

RUN pip install -r requirements.txt
# Installs the PostgreSQL adapter for Python
RUN pip install psycopg2
# Copies the rest of the application code into the container
COPY . .

RUN flask db upgrade
RUN flask seed all
CMD gunicorn app:app