"""empty message

Revision ID: 8c58dbf8a706
Revises: 4c07cc9f0bf0
Create Date: 2025-05-30 13:46:00.681274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c58dbf8a706'
down_revision = '4c07cc9f0bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_monster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_monster', schema=None) as batch_op:
        batch_op.drop_column('health')

    # ### end Alembic commands ###
